name: sql_speed_example
description: Example app demonstrating sql_speed usage.
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sql_speed:
    path: ../
  sqlite3_flutter_libs: ^0.5.0
